name: Django CI with Docker

on:
  push:
    branches:
      - main
      - staging
      - development
  pull_request:
    branches:
      - main
      - staging
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d db
        docker-compose -f docker-compose.yml up -d web

    - name: Run Tests
      run: |
        docker-compose exec web python manage.py test

    - name: Tear Down
      run: |
        docker-compose down

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Images
      run: |
        docker-compose -f docker-compose.yml build
