name: Django CI with Docker

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - staging
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker compose -f docker-compose.prod.yml up -d --build
        # docker compose -f docker-compose.prod.yml up -d web

    - name: Wait for 30 seconds
      run: sleep 30

    - name: Verify
      run: |
        echo "Docker image list"
        docker images
        echo "Docker container list"
        docker ps
        echo "Check the url"
        curl http://localhost:1337/

    - name: Tear Down
      run: |
        docker compose -f docker-compose.prod.yml down -v