name: Django CI with Docker

on:
  push:
    branches:
      # - main
      - staging
      - development
  pull_request:
    branches:
      # - main
      - staging
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker compose -f docker-compose.prod.yml up -d --build
        # docker compose -f docker-compose.prod.yml up -d web

    - name: Verify
      run: |
        curl localhost:1337

    - name: Tear Down
      run: |
        docker -f docker-compose.prod.yml down -v

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Images
      run: |
        docker compose -f docker-compose.yml build
