name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Production
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.PRODUCTION_HOST }}
        USER: ${{ secrets.PRODUCTION_USER }}
      run: |
        ssh -i "$SSH_PRIVATE_KEY" "$USER@$HOST" << 'EOF'
        cd /path/to/project
        docker-compose pull
        docker-compose up -d
        EOF
