name: Deploy to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker compose -f docker-compose.prod.yml up -d --build

    - name: Wait for 30 seconds
      run: sleep 30

    - name: Verify
      run: |
        echo "Docker image list"
        docker images
        echo "Docker container list"
        docker ps
        echo "Check the url"
        curl http://localhost:1337/

    - name: Tear Down
      run: |
        docker compose -f docker-compose.prod.yml down -v

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and Push Docker Image
      run: |
        docker tag django-docker-kub-web ${{ secrets.DOCKER_USERNAME }}/django-projects:web-v1.0.${GITHUB_RUN_NUMBER}
        docker tag django-docker-kub-web ${{ secrets.DOCKER_USERNAME }}/django-projects:web-latest
        docker push ${{ secrets.DOCKER_USERNAME }}/django-projects:web-v1.0.${GITHUB_RUN_NUMBER}
        docker push ${{ secrets.DOCKER_USERNAME }}/django-projects:web-latest